### ISSUE TITLE
Incorrect styling of transpose operator

### ISSUE THREAD

**Issue by elpollodiablo84** [mathworks/MATLAB-Language-grammar#10]
From [github.com/thedavidprice/language-matlab-octave/issues/19](https://github.com/thedavidprice/language-matlab-octave/issues/19), point 1.

There are two problems with the transpose operator:
```matlab
A = B';  % The variable B is also considered an operator.
A = {B, C}'; % The transpose operator has no styling at all.
```
As in #7, these issues are more evident in Atom with the language-matlab-octave extension.

**Comment by stestoll** [comment]
A few additional examples of this issue, for the transpose operator `.'` (`'` is the complex conjugate transpose operator)
```matlab
42.' % number is incorrectly highlighted
A.S.'  % S is incorrectly highlighted
S.'  % S is incorrectly highlighted
[S].' % correct
(S).' % correct
{S}.' % .' should be highlighted here, also comment is not identified 
'sdf'.'  % same here
```

**Comment by rlivings39** [comment]
These are great test cases! Thanks for adding them. Will get this fixed
