### ISSUE TITLE
Line continuation inside of `[]` breaks highlighting

### ISSUE THREAD

**Issue by rlivings39** [mathworks/MATLAB-Language-grammar#18]
Reported in https://github.com/Gimly/vscode-matlab/issues/98. Looks like the last line is interpreted as command syntax rather than an element of `[]`
```matlab
y = [ ... a comment
    x, ... another comment
    z ... should be a comment
];
```

**Comment by SimonMossmyr** [comment]
Additional information from [Gimly/vscode-matlab#98](https://github.com/Gimly/vscode-matlab/issues/98#issuecomment-550371226)
