### ISSUE TITLE
Wrong coloring of the last function argument when it is followed by ellipsis

### ISSUE THREAD

**Issue by vr050714** [mathworks/MATLAB-Language-grammar#23]
![multiline-instruction-coloring](https://user-images.githubusercontent.com/8076819/70906052-86bb1b80-2016-11ea-9d6b-42e66a15b3ee.PNG)

Probably, the same issue concerns arrays declaration as well

![multiline-instruction-coloring-2](https://user-images.githubusercontent.com/8076819/70906388-4c9e4980-2017-11ea-8791-d39767541062.PNG)

**Comment by vr050714** [comment]
The problem is that it expects comma operator in between variable and ellipsis.

**Comment by rlivings39** [comment]
Looks like the same issue as #18. If you inspect the syntax highlighting info in vscode with `Ctrl+Shift+P Developer: Inspect TM Scopes` and then move your cursor to the improperly highlighted line you'll see that the grammar is treating this the same way as MATLAB [command syntax](https://www.mathworks.com/help/matlab/matlab_prog/command-vs-function-syntax.html):

![vscodeBadCommand](https://user-images.githubusercontent.com/43882944/70936448-4bb5e980-2010-11ea-8b28-96ad54875d83.gif)

**Comment by vr050714** [comment]
That's interesting. Thanks!

**Comment by rlivings39** [comment]
Fixed by #28
