### ISSUE TITLE
no coloring if ellipsis appears in classdef with multiple inheritance

### ISSUE THREAD

**Issue by vr050714** [mathworks/MATLAB-Language-grammar#26]
![no-color-mixing-ellipsis](https://user-images.githubusercontent.com/8076819/70926198-bf222000-203d-11ea-915a-ce4aac35e864.PNG)

**Comment by rlivings39** [comment]
Likely due to the fact that TextMate grammars are single-line by default. One solution to this is to turn the `< BaseClass ...` into a block like we do for `if ... end, classdef ... end`.
```matlab
classdef MyClass < BaseClass1 & ...
                     BaseClass2 % <- no color
```

**Comment by vr050714** [comment]
BTW, MyClass and corresponding base classes, in this case, have the same semantic of class names. Should they be shown in different colors?

**Comment by rlivings39** [comment]
We could look at making them the same color. What would your preference be?

It looks like in the MATLAB grammar the scope is `entity.name.section.class.matlab` whereas for TypeScript:
```ts
class Base {}

class Child extends Base {

}
```
`Child` has `entity.name.type.class.ts`. In both MATLAB and TypeScript the base class has scope `entity.other.inherited-class.*`

If we think that this update is an improvement, it's technically feasible to do.

**Comment by vr050714** [comment]
To my mind, the corresponding theme selectors must be consistent with the other languages if it is possible otherwise they should not result in unexpected colors. (e.g. reduce number of different theme selectors to avoid collisions and distracting colors)

Highlighting of class definition has more problems:

<img width="320" alt="Screen Shot 2019-12-18 at 1 51 02 AM" src="https://user-images.githubusercontent.com/8076819/71042194-1f978700-213c-11ea-94e5-75e0beb9c561.png">

1. `classdef` is in `storage.type.class.matlab` scope what is good. But the last `end` keyword closing the class definition is recognized as `keyword.control.end.class.matlab`. And this "keyword.control" theme selector has collision with `keyword.control.end.if.matlab` scope.
2. `Sealed` modifier is in `variable.parameter.class.matlab` scope. This leading "variable" has collisions with the other scopes associated with variables like input/output function arguments. For comparison, it is `storage.modifier` in TypeScript or Java.
3. `Child` class name should be in `entity.name.type.class.matlab` scope instead of `entity.name.section.class.matlab` which is not recognized as theme selector by the way.
4. `function` keyword also gets "storage.control" theme selector similar to `classdef`.

**Comment by rlivings39** [comment]
Thanks for the detailed analysis. I split your observations out into https://github.com/mathworks/MATLAB-Language-grammar/issues/27
