### ISSUE TITLE
MATLAB grammar inconsistencies with other languages

### ISSUE THREAD

**Issue by rlivings39** [mathworks/MATLAB-Language-grammar#27]
Reported by @vr050714 in #26 

To my mind, the corresponding theme selectors must be consistent with the other languages if it is possible otherwise they should not result in unexpected colors. (e.g. reduce number of different theme selectors to avoid collisions and distracting colors)

Highlighting of class definition has more problems:

<img width="320" alt="Screen Shot 2019-12-18 at 1 51 02 AM" src="https://user-images.githubusercontent.com/8076819/71042194-1f978700-213c-11ea-94e5-75e0beb9c561.png">

1. `classdef` is in `storage.type.class.matlab` scope what is good. But the last `end` keyword closing the class definition is recognized as `keyword.control.end.class.matlab`. And this "keyword.control" theme selector has collision with `keyword.control.end.if.matlab` scope.
2. `Sealed` modifier is in `variable.parameter.class.matlab` scope. This leading "variable" has collisions with the other scopes associated with variables like input/output function arguments. For comparison, it is `storage.modifier` in TypeScript or Java.
3. `arg` variable looks different in method argument list and in condition of `if` statement where as it has the same meaning of local variable in both cases.
4. `Child` class name should be in `entity.name.type.class.matlab` scope instead of `entity.name.section.class.matlab` which is not recognized as theme selector by the way.
5. `function` keyword also gets "storage.control" theme selector similar to `classdef`.

**Comment by 4086606** [comment]
I have a local fork and I've made corrections and improvements to the token naming

I assume token naming should follow Textmate (w/ Sublime and Microsoft grammar) conventions? Otherwise theming will not work in Textmate-powered editors

I can open a PR by tomorrow with all these improvements

**Comment by 4086606** [comment]
I am shipping the improvements in the next 24 hours or so 🎉🎊
