### ISSUE TITLE
Single line block (e.g. try-catch) handling is broken

### ISSUE THREAD

**Issue by rlivings39** [mathworks/MATLAB-Language-grammar#36]
Reported from https://github.com/Gimly/vscode-matlab/issues/124#issuecomment-781451091

```matlab
try something; catch e; end

if true, 1, else 2, end
switch x, case 1, disp(1), end

try
  something
catch e
end
```

In the grammar all of the nested keywords like `catch, else, case` consume the rest of the line:

```xml
<string>(\s*)(?:^|[\s,;])(catch)\b(.*)?$\n?</string>
```

which breaks the end matching.

**Comment by 4086606** [comment]
This is honestly super complex and not meant to be done by a `match`...

It should be a try-catch meta scope that takes advantage of the `begin` `end` paradigms.

**Comment by SiFreZi** [comment]
Hi, I noticed that the try; catch; end highlighting is still not recognizing end as keyword.
Should this been solved already?

**Comment by SNDST00M** [comment]
Yes but I'm not sure what's breaking that
