### ISSUE TITLE
Incorrect handling of semicolon after command syntax

### ISSUE THREAD

**Issue by rlivings39** [mathworks/MATLAB-Language-grammar#7]
From https://github.com/thedavidprice/language-matlab-octave/issues/19

Consider he code:

```matlab
x = 1;
someCommand arg1; x = 1;
```
should treat `x = 1;` in the second line as typical code not as a string as part of the command. Notice that the `1` is not highlighted in the second line.

The difference is more pronounced in Atom with the [language-matlab-octave](thedavidprice/language-matlab-octave) extension:
![atomCommandSemicolon](https://user-images.githubusercontent.com/43882944/63987764-65eeaa80-caa7-11e9-8077-9fc094ff724f.png)

**Comment by 4086606** [comment]
https://github.com/mathworks/MATLAB-Language-grammar/blob/69dbf20c1eb19efd629c0438a2a493e60617e8de/Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage#L908-L932

Looking at the [help page](https://uk.mathworks.com/help/matlab/matlab_prog/command-vs-function-syntax.html), this seems overcomplicated. Dual command syntax is simple.. there's a `keyword.other`/`support.function` word and a string option at the end (terminated by `[\n;%]`). A check for missing `=` or `(` after the "word" is the only thing needed.

I'll see what comes of hacking at it

**Comment by 4086606** [comment]
Bugfix @ PR https://github.com/mathworks/MATLAB-Language-grammar/pull/37.

**Comment by 4086606** [comment]
Could you ping your colleague about the PR on Slack? I've corrected this issue and added enhancements: https://github.com/mathworks/MATLAB-Language-grammar/pull/37#issuecomment-843723493

**Comment by 4086606** [comment]
Resolved on #37.

**Comment by dklilley** [comment]
Closing - resolved by https://github.com/mathworks/MATLAB-Language-grammar/pull/37
